# -*- coding: utf-8 -*-

import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

print("starting")
browser = webdriver.PhantomJS()
print("browser binded to PhantomJS")
browser.get('https://qzone.qq.com')
print("browser.get started")
browser.switch_to_frame('login_frame')
print("switched to login frame")
browser.find_element_by_id('switcher_plogin').click()
print("clicked Switch button")
browser.find_element_by_id('u').clear()
print("User field clear")
browser.find_element_by_id('u').send_keys(QQ)
print("User field set")
browser.find_element_by_id('p').clear()
print("Passwd clear")
browser.find_element_by_id('p').send_keys(Passwd)
print("Passwd set")
browser.find_element_by_id('login_button').click()
print("Login button clicked")
time.sleep(5)
browser.find_element_by_id('aIcenter').click()
time.sleep(5)
print("we are in "+ browser.title)
print("wait 10s to complete loading page")
time.sleep(10)
#browser.find_element_by_xpath("//div[@id='QM_Mood_Poster_Inner']/div/div[4]/div[4]/a[2]/span").click()
#print("send clicked")
#print("input substitutor is now --* "+browser.find_element_by_id('$1_substitutor_content').get_attribute('innerHTML')+" *--")
if(browser.find_element_by_id('$1_content_content').get_attribute('innerHTML')==""):
  print("trying to click substitutor")
  browser.find_element_by_id('$1_substitutor_content').click()
  print("clicked. Now substitutor_content not displayed and content_content displayed")
  time.sleep(3)
else:
  print("content is previously set. trying to click it")
  browser.find_element_by_id('$1_content_content').click()
  print("clicked")
  time.sleep(2)
  print("trying to clear it")
  browser.find_element_by_id('$1_content_content').clear()
  print("and now it is cleared")
  time.sleep(2)
#print("content now is now --* "+browser.find_element_by_id('$1_content_content').get_attribute('innerHTML')+" *--")
#print("trying to click content")
#time.sleep(1)
browser.find_element_by_id('$1_content_content').click()
print("content clicked")
time.sleep(2)
print("trying to modify content")
#browser.find_element_by_id('$1_content_content').clear()
browser.find_element_by_id('$1_content_content').send_keys(u'测试中文字符')
browser.find_element_by_id('$1_content_content').send_keys(Keys.ENTER)
browser.find_element_by_id('$1_content_content').send_keys('auto-sent from selenium on RaspberryPi')
browser.find_element_by_id('$1_content_content').send_keys(Keys.ENTER)
browser.find_element_by_id('$1_content_content').send_keys('--Coded by WC')
print("tried")
time.sleep(3)
print("content is now --* "+browser.find_element_by_id('$1_content_content').get_attribute('innerHTML')+" *--")
time.sleep(3)
print("trying to CTRL+Enter to send")
browser.find_element_by_id('$1_content_content').send_keys(Keys.CONTROL,Keys.ENTER)
print("it should have been sent")
time.sleep(3)

print("Done!!!")
browser.quit()
